// Angular/haptic-button.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-haptic-button',
  standalone: true,
  imports: [CommonModule],
  template: `
    <button
      [class]="classes"
      [disabled]="disabled || loading"
      [attr.aria-busy]="loading"
      (click)="handleClick()"
    >
      <ng-content />
    </button>
  `,
  styles: [`
    :host { display: block; }
  `]
})
export class HapticButtonComponent {
  @Input() variant: 'primary' | 'secondary' | 'destructive' | 'plain' = 'primary';
  @Input() size: 'sm' | 'md' | 'lg' = 'md';
  @Input() fullWidth = false;
  @Input() loading = false;
  @Input() disabled = false;
  @Output() buttonClick = new EventEmitter<void>();

  get classes(): string {
    return [
      'apple-button',
      `apple-button--${this.variant}`,
      this.size !== 'md' && `apple-button--${this.size}`,
      this.fullWidth && 'apple-button--full',
      this.loading && 'apple-button--loading'
    ].filter(Boolean).join(' ');
  }

  handleClick(): void {
    if (this.disabled || this.loading) return;
    if (navigator.vibrate) navigator.vibrate(10);
    this.buttonClick.emit();
  }
}

// Svelte/HapticButton.svelte
<script>
  export let variant = 'primary';
  export let size = 'md';
  export let fullWidth = false;
  export let loading = false;
  export let disabled = false;

  $: classes = [
    'apple-button',
    `apple-button--${variant}`,
    size !== 'md' && `apple-button--${size}`,
    fullWidth && 'apple-button--full',
    loading && 'apple-button--loading'
  ].filter(Boolean).join(' ');

  function handleClick() {
    if (disabled || loading) return;
    if (navigator.vibrate) navigator.vibrate(10);
  }
</script>

<button
  class={classes}
  disabled={disabled || loading}
  aria-busy={loading}
  on:click={handleClick}
>
  <slot />
</button>
